# Generated by Django 5.0.7 on 2024-08-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_is_active_inventory_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='last_updated',
        ),
    ]
