# Generated by Django 5.0.7 on 2024-08-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
