# Generated by Django 5.0.7 on 2024-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
