# Generated by Django 5.0.7 on 2024-08-08 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customers_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$5FWntSTxGV9bnflldLhVYW$z5EtCvBMdj/jqvv/oemBfsghx9HhWtVlz3Rtv941FyA=', max_length=128),
        ),
    ]
