# Generated by Django 5.0.7 on 2024-08-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_otp_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$EQJDzwVf3883OxrZqKFBsQ$ODPlhM9micQ2laIx3KVzIP+0C8eTR0Of7jBJ91IdHNA=', max_length=128),
        ),
    ]
