# Generated by Django 5.0.7 on 2024-08-09 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customers_is_active_customers_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$GpKYZSfX5e0KQKBMp1oUor$UYdV7UnO6qBJOzdGdt5YSa9P805E4cOyl+3qJ7jV2zM=', max_length=128),
        ),
    ]
