# Generated by Django 5.0.7 on 2024-08-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_otp_expiry_time_alter_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$MUURcpvQ521X6aJORqZL4t$7onLxh1v351WTgGf+r4JZy+DV0tTCdqa/o5af6r0PkU=', max_length=128),
        ),
    ]
