# Generated by Django 5.0.7 on 2024-08-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$Wrzc1ICtcAJ7yEXJytzKiE$56kWPzVMRr5whrW1cergHL7Z7juh1ot50xn4pIVoyoc=', max_length=128),
        ),
    ]
