# Generated by Django 5.0.7 on 2024-08-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$gSkG6jbDwToFvYeJGZnn55$miYcs058OuX/vTkyNPUwDxNKapU2A3FsfqgmCXFa8gY=', max_length=128),
        ),
    ]
