# Generated by Django 5.0.7 on 2024-08-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$KidBuuON3K0BgGDjoydIo5$HV80z4OfUnVRm5AlAqRt3ODZ2EvmOc+Xfd2OoxKS1lw=', max_length=128),
        ),
    ]
