# Generated by Django 5.0.7 on 2024-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$DZbgLfQ0ijN1gnUjPjtXYm$fU7HO9yw43CkvwGs58oXApWPcUYOF3ZBF5YVPqSVEvk=', max_length=128),
        ),
    ]
