# Generated by Django 5.0.7 on 2024-08-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$R78tqQhHmauDMzOoHLZK0p$MdqTUiOgBKYvyjJ92Rp7Xd+FelvtImp2HtYzJf32vDc=', max_length=128),
        ),
    ]
