# Generated by Django 5.0.7 on 2024-08-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$HbToFUQmRquohKq2BvWygp$zsz5eZWLs2r6iYldrW0h+n2Z8pIEVQr6EBnoxK2SvC8=', max_length=128),
        ),
    ]
