# Generated by Django 5.0.7 on 2024-08-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$ZZxZpQHxDM6lkZ53rtXd2i$ha106JujwvPZDRXH90Y15G9uylEyvE54FEu8BGFPEWI=', max_length=128),
        ),
    ]
