# Generated by Django 5.0.7 on 2024-08-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$lstX9bqNdvSCtr0KRs0lxt$mJG0vL1tBVS2O4NM9dau2IRdZs0EytraGXkdas+Io/w=', max_length=128),
        ),
    ]
