# Generated by Django 5.0.7 on 2024-08-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$q9ufB36jJ9iAXsSDQcbdcC$tgnP1fzfswiAP/symW0j1jOdw0X4muvfi9DhChUr7X4=', max_length=128),
        ),
    ]
