# Generated by Django 5.0.7 on 2024-08-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$CAplMNX1VReCrLqLvPnbDy$qiLcw8r24TCfEUfwhJ9kHW0hg75JhH0fgpITh7RSScw=', max_length=128),
        ),
    ]
