# Generated by Django 5.0.7 on 2024-08-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$OwxMzvR7FveCZuTnn2uN69$5YHJGuPlEoKZOMIDVU3g47XuDW5Dgi3Q8vfxmtDZem4=', max_length=128),
        ),
    ]
