# Generated by Django 5.0.7 on 2024-08-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_categories_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
