# Generated by Django 5.0.7 on 2024-09-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categories_is_active_categories_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
