# Generated by Django 5.0.7 on 2024-08-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
